# Nova-3 - K3s Agent
# ARM64 compute module in Turing Pi 2 cluster
# Part of the Nova K3s cluster
{ ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "nova-3";

  # K3s agent
  # Requires serverAddr and token to be set after nova-1 is deployed
  # Token can be found on nova-1: sudo cat /var/lib/rancher/k3s/server/node-token
  services.k3s = {
    enable = true;
    role = "agent";
    serverAddr = "https://nova-1:6443";
    # tokenFile = "/var/lib/rancher/k3s/server/agent-token"; # Set after deployment
  };

  # Open firewall for K3s agent
  networking.firewall = {
    allowedTCPPorts = [
      10250 # Kubelet metrics
    ];
  };
}
