# RK1 Node 1 - Subnet Router & K3s Control Plane
# ARM64 compute module in Turing Pi 2 cluster
# This node serves as the Tailscale subnet router for the cluster
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  # Set hostname
  networking.hostName = "rk1-node1";

  # Tailscale subnet router configuration
  # This node advertises K3s subnets to your tailnet and routes traffic through Mullvad
  #
  # After deployment, run:
  #   sudo tailscale up --advertise-routes=10.42.0.0/16,10.43.0.0/16 --accept-dns=false
  #
  # Then approve routes in Tailscale admin console and set Mullvad exit node:
  #   tailscale set --exit-node=<mullvad-node>
  services.tailscale = {
    useRoutingFeatures = "both"; # "both" = can advertise routes AND use exit nodes
  };

  # Enable IP forwarding for subnet routing
  boot.kernel.sysctl = {
    "net.ipv4.ip_forward" = 1;
    "net.ipv6.conf.all.forwarding" = 1;
  };
}
