# Nova-1 - K3s Control Plane (Server)
# ARM64 compute module in Turing Pi 2 cluster
# Part of the Nova K3s cluster
{ ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "nova-1";

  # K3s server (control plane)
  # After first boot, get the node token from:
  #   sudo cat /var/lib/rancher/k3s/server/node-token
  services.k3s = {
    enable = true;
    role = "server";
    extraFlags = toString [
      "--disable=traefik" # We'll deploy our own Traefik
      "--disable=servicelb" # Use MetalLB or similar instead
      "--flannel-backend=host-gw" # Better performance on local network
      "--tls-san=nova-1" # Add hostname to TLS cert
    ];
  };

  # Open firewall for K3s
  networking.firewall = {
    allowedTCPPorts = [
      6443 # Kubernetes API
      10250 # Kubelet metrics
    ];
  };
}
