# RK1 Node 2 - Individual node configuration
# ARM64 compute module in Turing Pi 2 cluster
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  # Set hostname
  networking.hostName = "rk1-node2";
}
