# Zenith-1 - K3s Control Plane (Server)
# ARM64 compute module in Turing Pi 2 cluster
# Part of the Zenith k3s cluster
{ config, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "zenith-1";

  # K3s token from SOPS
  sops.secrets."zenith/k3s_token" = { };

  # K3s server (control plane)
  services.k3s = {
    enable = true;
    role = "server";
    tokenFile = config.sops.secrets."zenith/k3s_token".path;
    extraFlags = toString [
      "--disable=traefik" # We'll deploy our own Traefik
      "--disable=servicelb" # Use MetalLB or similar instead
      "--flannel-backend=host-gw" # Better performance on local network
      "--tls-san=zenith-1" # Add hostname to TLS cert
    ];
  };

  # Open firewall for K3s
  networking.firewall = {
    allowedTCPPorts = [
      6443 # Kubernetes API
      10250 # Kubelet metrics
    ];
  };
}
