# GLaDOS - Linux Laptop Configuration
# ThinkPad X1 Carbon - x86_64-linux
{
  config,
  inputs,
  pkgs,
  ...
}:

{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko module
    inputs.disko.nixosModules.disko

    # Disko disk configuration
    ./disks.nix

    # Base NixOS configuration
    ../../../modules/nixos/common.nix

    # SOPS for secrets management
    ../../../modules/nixos/sops.nix
  ];

  # Host specification
  hostSpec = {
    hostName = "glados";
    isLaptop = true;
  };

  # Set hostname
  networking.hostName = "glados";

  system.stateVersion = "24.05";
}
