# Sephiroth - RK1 Development Server
# ARM64 compute module in Turing Pi 2 cluster
# Full development environment with Tailscale access
{ pkgs, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  # Override hostSpec for dev server (not a minimal cluster node)
  hostSpec = {
    isMinimal = false;
    isServer = true;
    isClusterNode = false;
  };

  networking.hostName = "sephiroth";

  # Tailscale configuration - full device with exit node support
  # After deployment, run:
  #   sudo tailscale up --accept-dns=false
  # Then set Mullvad exit node:
  #   tailscale set --exit-node=<mullvad-node>
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "client"; # Use exit nodes (Mullvad)
  };

  # Additional dev packages at system level
  environment.systemPackages = with pkgs; [
    neovim
    git
  ];
}
