# Ganon - Gaming PC Configuration
# x86_64-linux with NVIDIA GPU, dual-boot with Windows
{
  config,
  inputs,
  pkgs,
  ...
}:

{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko module
    inputs.disko.nixosModules.disko

    # Disko disk configuration
    ./disks.nix

    # Base NixOS configuration
    ../../../modules/nixos/common.nix

    # SOPS for secrets management
    ../../../modules/nixos/sops.nix
  ];

  # Host specification
  hostSpec = {
    hostName = "ganon";
    isGaming = true;
  };

  # Set hostname
  networking.hostName = "ganon";

  # Bootloader - GRUB with EFI for dual-boot with Windows
  boot.loader = {
    grub = {
      enable = true;
      useOSProber = true;
      efiSupport = true;
      device = "nodev";
      theme = "${pkgs.catppuccin-grub}/share/grub/themes/catppuccin-mocha-grub-theme";
    };
    efi.canTouchEfiVariables = true;
  };

  # NVIDIA drivers (hardware requirement)
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false; # Use proprietary driver
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Enable OpenGL (required for NVIDIA)
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Gaming performance optimization (system-level)
  programs.gamemode = {
    enable = true;
    enableRenice = true;
    settings = {
      general = {
        softrealtime = "auto";
        renice = 15;
      };
    };
  };

  # Gaming-specific kernel settings
  boot.kernel.sysctl = {
    "vm.max_map_count" = 2147483642; # Helps with gaming performance
  };

  # Hyprland (Wayland compositor)
  programs.hyprland = {
    enable = true;
    xwayland.enable = true; # For X11 apps (Steam, etc.)
  };

  # Login manager
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --remember --cmd Hyprland";
        user = "greeter";
      };
    };
  };

  # Essential packages for Hyprland setup
  environment.systemPackages = with pkgs; [
    kitty # Terminal
    waybar # Status bar
    wofi # App launcher
    mako # Notifications
    grim # Screenshot
    slurp # Screen region select
    wl-clipboard # Clipboard
    swww # Wallpaper
  ];

  # Enable sound (PipeWire)
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  system.stateVersion = "24.05";
}
