# Ganon - Gaming PC Configuration
# x86_64-linux with NVIDIA GPU, dual-boot with Windows
{
  config,
  inputs,
  pkgs,
  ...
}:

{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko module
    inputs.disko.nixosModules.disko

    # Disko disk configuration
    ./disks.nix

    # Base NixOS configuration
    ../../../modules/nixos/common.nix

    # SOPS for secrets management
    ../../../modules/nixos/sops.nix
  ];

  # Host specification
  hostSpec = {
    hostName = "ganon";
    isGaming = true;
  };

  # Set hostname
  networking.hostName = "ganon";

  # Boot configuration
  boot = {
    # GRUB bootloader with EFI for dual-boot with Windows
    loader = {
      grub = {
        enable = true;
        useOSProber = true;
        efiSupport = true;
        device = "nodev";
        # Theme handled by catppuccin module
        gfxmodeEfi = "2560x1440";
        gfxpayloadEfi = "keep"; # Pass GRUB resolution to Linux
      };
      efi.canTouchEfiVariables = true;
    };

    # Plymouth boot splash (pretty LUKS password prompt)
    plymouth = {
      enable = true;
      # Use a nice monospace font for password input
      font = "${pkgs.jetbrains-mono}/share/fonts/truetype/JetBrainsMono-Regular.ttf";
    };

    # Enable systemd in initrd for graphical LUKS password prompt
    initrd.systemd.enable = true;

    # Silent boot (hide text, show plymouth)
    consoleLogLevel = 3;
    initrd.verbose = false;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "udev.log_priority=3"
      "rd.systemd.show_status=auto"
      # NVIDIA framebuffer for Plymouth at native resolution
      "nvidia_drm.fbdev=1"
      # Preserve VRAM during suspend (required for sleep/wake)
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
    ];

    # Gaming-specific kernel settings
    kernel.sysctl = {
      "vm.max_map_count" = 2147483642; # Helps with gaming performance
    };

    # Required for Sunshine virtual input devices
    kernelModules = [ "uinput" ];
  };

  # NVIDIA drivers (hardware requirement)
  hardware.nvidia = {
    modesetting.enable = true;
    # Enable power management for proper sleep/wake
    powerManagement.enable = true;
    powerManagement.finegrained = false;
    # Try proprietary modules if open has sleep issues (uncomment to switch)
    open = true; # Use open kernel modules (recommended for RTX 30 series+)
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # NVIDIA suspend/resume services (critical for sleep/wake)
  # These save/restore GPU state during sleep
  systemd.services = {
    nvidia-suspend = {
      enable = true;
      wantedBy = [ "suspend.target" ];
    };
    nvidia-resume = {
      enable = true;
      wantedBy = [ "suspend.target" ];
    };
    nvidia-hibernate = {
      enable = true;
      wantedBy = [ "hibernate.target" ];
    };
  };

  # Enable OpenGL (required for NVIDIA)
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [ nvidia-vaapi-driver ];
  };

  # Gaming performance optimization (system-level)
  programs.gamemode = {
    enable = true;
    enableRenice = true;
    settings = {
      general = {
        softrealtime = "auto";
        renice = 15;
      };
    };
  };

  # Hyprland (Wayland compositor)
  programs.hyprland = {
    enable = true;
    xwayland.enable = true; # For X11 apps (Steam, etc.)
  };

  # XDG Portal (screen sharing, file pickers, etc.)
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };

  # NVIDIA + Wayland environment variables (critical for Hyprland)
  environment.sessionVariables = {
    # Hardware cursors not yet working on NVIDIA
    WLR_NO_HARDWARE_CURSORS = "1";
    # Use NVIDIA GBM backend
    GBM_BACKEND = "nvidia-drm";
    # Use NVIDIA driver for Wayland
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    # Enable Wayland for Electron apps
    NIXOS_OZONE_WL = "1";
    # Qt apps use Wayland
    QT_QPA_PLATFORM = "wayland";
    # Firefox uses Wayland
    MOZ_ENABLE_WAYLAND = "1";
  };

  # Essential packages for Hyprland setup
  environment.systemPackages = with pkgs; [
    kitty # Terminal
    waybar # Status bar
    wofi # App launcher
    mako # Notifications
    grim # Screenshot
    slurp # Screen region select
    wl-clipboard # Clipboard
    swww # Wallpaper
    liquidctl # Water cooling control (farbwerk 360, OCTO)
    openrgb-with-all-plugins # RGB control (motherboard, etc.)
  ];

  # Enable sound (PipeWire)
  security.rtkit.enable = true;

  # udev rules
  services.udev = {
    # Sunshine virtual input (uinput)
    extraRules = ''
      KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", GROUP="input", MODE="0660"
    '';
    # liquidctl rules for Aquacomputer devices (OCTO, Farbwerk 360)
    packages = [ pkgs.liquidctl ];
  };

  # Services
  services = {
    # NVIDIA driver - xserver.enable required to load drivers even for Wayland
    xserver = {
      enable = true;
      videoDrivers = [ "nvidia" ];
    };

    # Sunshine for remote desktop (Moonlight client)
    sunshine = {
      enable = true;
      autoStart = true;
      capSysAdmin = true; # Required for Wayland capture
      openFirewall = true;
    };

    # Login manager
    greetd = {
      enable = true;
      settings = {
        default_session = {
          command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --remember --sessions ${config.services.displayManager.sessionData.desktops}/share/wayland-sessions";
          user = "greeter";
        };
      };
    };

    # OpenRGB for motherboard RGB control
    hardware.openrgb.enable = true;

    # PipeWire audio
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
    };
  };

  system.stateVersion = "24.05";
}
