# Zenith-0 - K3s Control Plane (Server)
# ARM64 compute module in Turing Pi 2 cluster
#
# Formerly "sephiroth", the dev server. That name is reserved for a new dev
# machine; this module is now a pure cluster node.
{ config, lib, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "zenith-0";

  # Keep the non-cluster disk layout. This node inherited the dev server's
  # partitioning: a single btrfs partition on the NVMe carrying /data and /nix.
  # The cluster layout would add a 200G ext4 /var/lib/longhorn plus /rancher and
  # /kubelet subvolumes — provisioning for a storage node, which a control plane
  # is not. disko only partitions at install time, so adopting it would mean
  # reflashing the eMMC purely to host Longhorn replicas this node doesn't need.
  #
  # isClusterNode gates exactly two things (disks.nix and the SOPS user age key
  # in modules/nixos/sops.nix) and does NOT gate k3s, so the server config below
  # is unaffected. Revisit only if zenith-0 should carry Longhorn storage.
  hostSpec.isClusterNode = lib.mkForce false;

  # /nix lives on a btrfs subvolume on the NVMe, so the initrd must be able to
  # mount btrfs before it can find the system closure. boot.supportedFilesystems
  # only covers the running system — the initrd keeps its own list, and btrfs was
  # absent from it, so the boot dropped to an emergency shell with "Failed to
  # start Find NixOS closure". nvme was already present; btrfs was the gap.
  boot.initrd.supportedFilesystems = [ "btrfs" ];

  # K3s token from SOPS
  sops.secrets."zenith/k3s_token" = { };

  # K3s server (control plane).
  #
  # --cluster-init selects embedded etcd instead of the default SQLite backend.
  # zenith-1 ran without it, which is why that cluster could never gain a second
  # server without migrating its datastore first. Starting on etcd keeps the
  # option open.
  services.k3s = {
    enable = true;
    role = "server";
    tokenFile = config.sops.secrets."zenith/k3s_token".path;
    extraFlags = toString [
      "--cluster-init"
      "--disable=traefik" # We'll deploy our own Traefik
      "--disable=servicelb" # Use MetalLB or similar instead
      "--flannel-backend=host-gw" # Better performance on local network
      "--tls-san=zenith-0" # Add hostname to TLS cert
    ];
  };

  # Open firewall for K3s
  networking.firewall = {
    allowedTCPPorts = [
      6443 # Kubernetes API
      2379 # etcd client
      2380 # etcd peer
      9100 # Prometheus node exporter
      10250 # Kubelet metrics
    ];
  };
}
