# Sephiroth - RK1 Development Server
# ARM64 compute module in Turing Pi 2 cluster
# Full development environment with Tailscale access
{ pkgs, lib, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  # Override hostSpec for dev server (not a minimal cluster node)
  hostSpec = {
    isMinimal = lib.mkForce false;
    isServer = true;
    isClusterNode = lib.mkForce false;
  };

  networking.hostName = "sephiroth";

  # Additional dev packages at system level
  environment.systemPackages = with pkgs; [
    neovim
    git
  ];
}
