# Zenith-0 - K3s Control Plane (Server)
# ARM64 compute module in Turing Pi 2 cluster
#
# Formerly "sephiroth", the dev server. That name is reserved for a new dev
# machine; this module is now a pure cluster node.
{ config, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "zenith-0";

  # K3s token from SOPS
  sops.secrets."zenith/k3s_token" = { };

  # K3s server (control plane).
  #
  # --cluster-init selects embedded etcd instead of the default SQLite backend.
  # zenith-1 ran without it, which is why that cluster could never gain a second
  # server without migrating its datastore first. Starting on etcd keeps the
  # option open.
  services.k3s = {
    enable = true;
    role = "server";
    tokenFile = config.sops.secrets."zenith/k3s_token".path;
    extraFlags = toString [
      "--cluster-init"
      "--disable=traefik" # We'll deploy our own Traefik
      "--disable=servicelb" # Use MetalLB or similar instead
      "--flannel-backend=host-gw" # Better performance on local network
      "--tls-san=zenith-0" # Add hostname to TLS cert
    ];
  };

  # Open firewall for K3s
  networking.firewall = {
    allowedTCPPorts = [
      6443 # Kubernetes API
      2379 # etcd client
      2380 # etcd peer
      9100 # Prometheus node exporter
      10250 # Kubelet metrics
    ];
  };
}
