# Zenith-2 - K3s Agent
# ARM64 compute module in Turing Pi 2 cluster
# Part of the Zenith k3s cluster
{ config, ... }:
{
  imports = [
    # Hardware configuration (will be generated by nixos-anywhere)
    # ./hardware-configuration.nix

    # Disko disk configuration
    ../common/disks.nix

    # Shared RK1 base configuration
    ../common
  ];

  networking.hostName = "zenith-2";

  # K3s token from SOPS
  sops.secrets."zenith/k3s_token" = { };

  # K3s agent
  services.k3s = {
    enable = true;
    role = "agent";
    serverAddr = "https://zenith-1:6443";
    tokenFile = config.sops.secrets."zenith/k3s_token".path;
  };

  # Open firewall for K3s agent
  networking.firewall = {
    allowedTCPPorts = [
      10250 # Kubelet metrics
    ];
  };
}
